FROM python:3.12 AS builder

WORKDIR /app
COPY . .

ENV POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  POETRY_HOME='/usr/local' \
  POETRY_VERSION=1.8.3

RUN curl -sSL https://install.python-poetry.org | python3 -
COPY poetry.lock pyproject.toml /app/
RUN poetry install

RUN poetry run reflex export --frontend-only --no-zip

FROM nginx

COPY --from=builder /app/.web/_static /usr/share/nginx/html
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
